// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Compiler.CodeDom.dll")>]
[<assembly: AssemblyProductAttribute("FSharp.Compiler.CodeDom")>]
[<assembly: AssemblyCompanyAttribute("F# Software Foundation, Microsoft")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2004 - 2017 Microsoft")>]
[<assembly: AssemblyDescriptionAttribute("A limited CodeDom implementation for F#")>]
[<assembly: AssemblyVersionAttribute("1.0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Compiler.CodeDom.dll"
    let [<Literal>] AssemblyProduct = "FSharp.Compiler.CodeDom"
    let [<Literal>] AssemblyCompany = "F# Software Foundation, Microsoft"
    let [<Literal>] AssemblyCopyright = "Copyright © 2004 - 2017 Microsoft"
    let [<Literal>] AssemblyDescription = "A limited CodeDom implementation for F#"
    let [<Literal>] AssemblyVersion = "1.0.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.0.1"
