
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

// Namespace Comment
namespace Namespace1
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptionedc88ded4d194b1981f8b01a25b48507 of obj
    exception ReturnNoneExceptionedc88ded4d194b1981f8b01a25b48507
    [<AutoOpen>]
    module FuncConvertFinalOverloadedc88ded4d194b1981f8b01a25b48507 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        // Outer Type Comment
        
        Class1 = class
            new() as this =
                {
                }
            // Method 2 Comment
            // Method 2 Comment
            abstract Method2 : unit -> unit
            default this.Method2  () =
                ()
            
            abstract Method1 : unit -> unit
            default this.Method1  () =
                ()
        end