
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

namespace NSPC
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptionac702beeb9d343849d9048a4aa37e811 of obj
    exception ReturnNoneExceptionac702beeb9d343849d9048a4aa37e811
    [<AutoOpen>]
    module FuncConvertFinalOverloadac702beeb9d343849d9048a4aa37e811 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        
        TEST = class
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            val mutable PublicField:int[]
            new() as this =
                {
                } then
                        this.PublicField <- ([| 0; 0; 0; 0; 0; 0; 0 |] : int[]);
            
            abstract Item : int -> int with get,set
            default this.Item
                with get(i:int) : int =
                    this.PublicField.[i]
                and set(i:int, value:int) : unit =
                    this.PublicField.[i] <- value
            
            
            abstract Item : int * int -> int with get,set
            default this.Item
                with get(a:int, b:int) : int =
                    this.PublicField.[(a + b)]
                and set(a:int, b:int, value:int) : unit =
                    this.PublicField.[(a + b)] <- value
        end
    
    and
        
        UseTEST = class
            new() as this =
                {
                }
            abstract TestMethod : int -> int
            default this.TestMethod  (i:int) =
                let mutable i = i
                let mutable (temp:TEST) = new TEST()
                temp.set_Item(1, i)
                temp.set_Item(2, 4, 83)
                (temp.[1] + temp.[2, 4])
        end